#modificar el banner para que no tome el default
banner:
  location: classpath:banner-omr.txt # Banner file location.
  
#para conecar con postgresql  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db 
    username: postgres
    password: comr040488
  jpa:    
    hibernate:
      ddl-auto: update
      show-sql: true         
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
       
 
